server:
  port: 30200

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # 确认消息已发送到交换机(Exchange); 2.2.x改为 publisher-confirm-type: correlated
    publisher-confirms: true
    # 确认消息已发送到队列(Queue)
    publisher-returns: true
#    listener:
#      simple:
#        # 手动确认
#        acknowledge-mode: manual
#        # 拒绝消息是否重回队列
#        default-requeue-rejected: true